[package]
name = "sandoseer"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "AI MEV Oracle for Solana - Autonomous MEV detection and execution system"

[dependencies]
# Local dependencies
listen-engine = { path = "listen/listen-engine" }

# Solana dependencies
solana-sdk = "1.17"
solana-client = "1.17"
solana-program = "1.17"
solana-transaction-status = "1.17"
solana-rpc-client = "1.17"
solana-rpc-client-api = "1.17"
solana-account-decoder = "1.17"
solana-pubsub-client = "1.17"

# Async runtime
tokio = { version = "1.36", features = ["full"] }
futures = "0.3"
futures-util = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# HTTP client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Configuration
config = "0.14"
dotenv = "0.15"

# Utilities
chrono = "0.4"
rand = "0.8"
dashmap = "5.5"
parking_lot = "0.12"
base64 = "0.21"

# Metrics
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Async traits
async-trait = "0.1"

curve25519-dalek = "=3.2.1"

[dev-dependencies]
tokio-test = "0.4"
pretty_assertions = "1.4"
